# 46장 제너레이터와 async/await

## 46.1 제너레이터란?
ES6에서 도입된 제너레이터는 코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수다. 일반 함수와 다음과 같은 차이가 있다.

1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.
2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.
3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.

## 46.2 제너레이터 함수의 정의
제너레이터 함수는 function* 키워드로 선언한다. 그리고 하나 이상의 yield 표현식을 포함한다. 이를 제외하면 일반 함수를 정의하는 방법과 같다.
주의할 점은 화살표 함수로 정의할 수 없고 new 연산자와 함께 생성자 함수로 호출할 수 없다. 
```js
function* genDecFunc(){
 yield 1;
}
const obj = {
  * genObjMethod(){
    yield 1;
  }
}
const MyClass {
  * genClsMethod(){
    yield 1;
  }
}
```
## 46.3 제너레이터 객체
제너레이터 함수를 호출하면 일반 함수처럼 함수 코드 블록을 실행하는 것이 아니라 제너레이터 객체를 생성해 반환한다.
제너레이터 함수가 반환한 제너레이터 객체는 이터러블이면서 동시에 이터레이터다.

제너레이터 객체는 next 메서드를 갖는 이터레이터지만 이터레이터에는 없는 return, throw 메서드를 갖는다. 
제너레이터 객체의 세 개의 메서드를 호출하면 다음과 같이 동작한다.

- next 메서드를 호출하면 제너레이터 함수의 yield 표현식까지 코드 블록을 실행하고 yield된 값을 value 프로퍼티 값으로, false를 done 프로퍼티 값으로
갖는 이터레이터 리절트 객체를 반환한다.
- return 메서드를 호출하면 인수로 전달받은 값을 value 프로퍼티 값으로, true를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.
- throw 메서드를 호출하면 인수로 전달받은 에러를 발생시키고 undefined를 value 프로퍼티 값으로,
  true를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.

## 46.4 제너레이터의 일시 중지와 재개 
제너레이터는 yield 키워드와 next 메서드를 통해 실행을 일시 중지했다가 필요한 시점에 다시 재개할 수 있다. 
함수 호출자에게 제어권을 양도하여 필요한 시점에 함수 실행을 재개할 수 있다.

제너레이터 함수를 호출하면 제너레이터 함수의 코드 블록이 실행되는 것이 아니라 제너레이터 객체를 반환한다고 했는데, 이터러블이면서 동시에 이터레이터인 제너레이터 객체는 next 메서드를 갖는다.
제너레이터 객체의 next 메서드를 호출하면 제너레이터 함수의 코드 블록을 실행한다. 

단, 일반 함수처럼 한 번에 코드 블록의 모든 코드를 일괄 실행하는 것이 아니라 yield 표현식까지만 실행한다. yield 키워드는 제너레이터 함수의 실행을 일시 중지시키거나 yield 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환한다.

이터레이터의 next 메서드와 달리 제너레이터 객체의 next 메서드에는 인수를 전달할 수 있다. 제너레이터 객체의 next 메서드에 전달한 인수는 제너레이터 함수의 yield 표현식의 평가 결과가 할당되지 않는 것에 주의하자.

## 46.5 제너레이터의 활용
### 46.5.1 이터러블의 구현
제너레이터 함수를 사용하면 이터레이션 프로토콜을 준수해 이터러블을 생성하는 방식보다 간단히 이터러블을 구현할 수 있다.
### 46.5.2 비동기 처리
제너레이터 함수는 next 메서드와 yield 표현식을 통해 함수 호출자와 함수의 상태를 주고받을 수 있다. 이러한 특성을 활용하면 프로미스를 사용한 비동기처리를 동기처리처럼 구현할 수 있다.
즉, 프로미스의 후속 처리 메서드 then/catch/finally 없이 비동기 처리 결과를 반환하도록 구현할 수 있다. 

## 46.6 async/await
제너레이터를 사용해 비동기 처리를 동기 처리처럼 동작하도록 구현했지만 코드가 무척이나 장황해지고 가독성도 나빠진다. ES8에선 제너레이터보다 간단하고 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있는 async/await가 도입되었다.

async/await는 프로미스를 기반으로 동작하는데 프로미스의 then/catch/finally 후속 처리 메서드에 콜백 함수를 전달해 비동기 처리 결과를 후속 처리할 필요 없이 마치 동기 처리처럼 프로미스를 사용할 수 있다.
즉, 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다. 
### 46.6.1 async 함수
await 키워드는 반드시  async 함수 내부에서 사용해야한다. async 함수는 async 키워드를 사용해 정의하며 언제나 프로미스를 반환한다. 
async 함수가 명시적으로 프로미스를 반환하지 않더라도 async 함수는 암묵적으로 반환값을 resolve하는 프로미스를 반환한다. 
주의해야할 점은 클래스의 constructor 메서드는 async 메서드가 될 수 없다. 클래스의 constructor 메서드는 인스턴스를 반환해야 하지만 async 함수는 언제나 프로미스를 반환해야한다. 
### 46.6.2 await 키워드
await 키워드는 프로미스가 settled 상태가 될 때까지 대기하다 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환한다. await 키워드는 반드시 프로미스 앞에서 사용해야한다.

모든 프로미스에 await 키워드를 사용하는 것은 주의해야한다. 
```js
async function foo(){
  const a = await new Propmise(resolve => setTimeout(() => resolve(1),3000);
  const b = await new Propmise(resolve => setTimeout(() => resolve(2),2000);
  const c = await new Propmise(resolve => setTimeout(() => resolve(3),1000);

  console.log([a,b,c]); //[1,2,3]
}
foo();
```
위의 코드는 종료될 때까지 약 6초가 걸린다. foo 함수가 수행하는 3개의 비동기 처리는 서로 연관이 없이 개별적으로 수행되는 비동기 처리이므로 앞선 비동기 처리가 완료될 때까지 대기해 순차적으로 처리할 필요가 없다.
따라서 다음 코드와 같이 수정하는게 좋다.
```js
async function foo(){
  const res = await.Promise.all([
    new Promise(resolve => setTimeout(() => resolve(1),3000);
    new Promise(resolve => setTimeout(() => resolve(2),2000);
    new Promise(resolve => setTimeout(() => resolve(3),1000);
  ]);
  console.log(res); //[1,2,3]
}
foo();
```
### 46.6.3 에러 처리
비동기 처리를 위한 콜백 패턴의 단점 중 가장 심각한 것은 에러 처리가 곤란하다는 것이다. 에러는 호출자 방향 즉, 콜 스택의 아래 방향으로 전파된다.
하지만 비동기 함수의 콜백 함수를 호출한 것은 비동기 함수가 아니기 때문에 try...catch 문을 사용해 에러를 캐치할 수 없다.
```js
try{
  setTimeout(()=> {throw new Error('Error');},1000)
}catch(e){
  //잡아내지 못함
  console.error('캐치한 에러',e);
}
```
반면 async/await에서 에러처리는 try...catch 문을 사용할 수 있다. 콜백 함수를 인수로 전달받는 비동기 함수와는 달리 프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 호출자가 명확한다.

async 함수 내에서 catch 문을 사용해 에러처리를 하지 않으면 async 함수는 발생한 에러를 reject하는 프로미스를 반환한다.
따라서 async 함수를 호출하고 Promiose.prototype.catch 후속 처리 메서드를 사용해 에러를 캐치할 수도 있다.
